name: doerly

services:
  main.service:
    container_name: doerly-main-service
    build:
      context: ./src/main-service/
      dockerfile: ./Doerly.WebHost/Dockerfile
    restart: always
    ports:
      - 5000:8080
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
    depends_on:
      - db
    #volumes:
      #- ./src/main-service/Doerly.WebHost/appsettings.${ASPNETCORE_ENVIRONMENT}.json:/app/appsettings.json   


  db:
    image: postgres:14.15-alpine
    container_name: doerly-db
    restart: always
    ports:
    - 5432:5432
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - doerly-db-data:/var/lib/postgresql/data

volumes:
  doerly-db-data: