using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Doerly.Module.Profile.DataAccess.Migrations
{
    /// <inheritdoc />
    /// <inheritdoc />
    public partial class PopulateLanguages : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                INSERT INTO profile.language (name, code, date_created, last_modified_date) VALUES
                  ('Afar', 'aa', NOW(), NOW()),
                  ('Abkhazian', 'ab', NOW(), NOW()),
                  ('Avestan', 'ae', NOW(), NOW()),
                  ('Afrikaans', 'af', NOW(), NOW()),
                  ('Akan', 'ak', NOW(), NOW()),
                  ('Amharic', 'am', NOW(), NOW()),
                  ('Aragonese', 'an', NOW(), NOW()),
                  ('Arabic', 'ar', NOW(), NOW()),
                  ('Assamese', 'as', NOW(), NOW()),
                  ('Avaric', 'av', NOW(), NOW()),
                  ('Aymara', 'ay', NOW(), NOW()),
                  ('Azerbaijani', 'az', NOW(), NOW()),
                  ('Bashkir', 'ba', NOW(), NOW()),
                  ('Belarusian', 'be', NOW(), NOW()),
                  ('Bulgarian', 'bg', NOW(), NOW()),
                  ('Bihari languages', 'bh', NOW(), NOW()),
                  ('Bislama', 'bi', NOW(), NOW()),
                  ('Bambara', 'bm', NOW(), NOW()),
                  ('Bengali', 'bn', NOW(), NOW()),
                  ('Tibetan', 'bo', NOW(), NOW()),
                  ('Breton', 'br', NOW(), NOW()),
                  ('Bosnian', 'bs', NOW(), NOW()),
                  ('Catalan', 'ca', NOW(), NOW()),
                  ('Chechen', 'ce', NOW(), NOW()),
                  ('Chamorro', 'ch', NOW(), NOW()),
                  ('Corsican', 'co', NOW(), NOW()),
                  ('Cree', 'cr', NOW(), NOW()),
                  ('Czech', 'cs', NOW(), NOW()),
                  ('Church Slavic', 'cu', NOW(), NOW()),
                  ('Chuvash', 'cv', NOW(), NOW()),
                  ('Welsh', 'cy', NOW(), NOW()),
                  ('Danish', 'da', NOW(), NOW()),
                  ('German', 'de', NOW(), NOW()),
                  ('Divehi', 'dv', NOW(), NOW()),
                  ('Dzongkha', 'dz', NOW(), NOW()),
                  ('Ewe', 'ee', NOW(), NOW()),
                  ('Greek', 'el', NOW(), NOW()),
                  ('English', 'en', NOW(), NOW()),
                  ('Esperanto', 'eo', NOW(), NOW()),
                  ('Spanish', 'es', NOW(), NOW()),
                  ('Estonian', 'et', NOW(), NOW()),
                  ('Basque', 'eu', NOW(), NOW()),
                  ('Persian', 'fa', NOW(), NOW()),
                  ('Fulah', 'ff', NOW(), NOW()),
                  ('Finnish', 'fi', NOW(), NOW()),
                  ('Fijian', 'fj', NOW(), NOW()),
                  ('Faroese', 'fo', NOW(), NOW()),
                  ('French', 'fr', NOW(), NOW()),
                  ('Western Frisian', 'fy', NOW(), NOW()),
                  ('Irish', 'ga', NOW(), NOW()),
                  ('Scottish Gaelic', 'gd', NOW(), NOW()),
                  ('Galician', 'gl', NOW(), NOW()),
                  ('Guarani', 'gn', NOW(), NOW()),
                  ('Gujarati', 'gu', NOW(), NOW()),
                  ('Manx', 'gv', NOW(), NOW()),
                  ('Hausa', 'ha', NOW(), NOW()),
                  ('Hebrew', 'he', NOW(), NOW()),
                  ('Hindi', 'hi', NOW(), NOW()),
                  ('Hiri Motu', 'ho', NOW(), NOW()),
                  ('Croatian', 'hr', NOW(), NOW()),
                  ('Haitian Creole', 'ht', NOW(), NOW()),
                  ('Hungarian', 'hu', NOW(), NOW()),
                  ('Armenian', 'hy', NOW(), NOW()),
                  ('Herero', 'hz', NOW(), NOW()),
                  ('Interlingua', 'ia', NOW(), NOW()),
                  ('Indonesian', 'id', NOW(), NOW()),
                  ('Interlingue', 'ie', NOW(), NOW()),
                  ('Igbo', 'ig', NOW(), NOW()),
                  ('Sichuan Yi', 'ii', NOW(), NOW()),
                  ('Inupiaq', 'ik', NOW(), NOW()),
                  ('Ido', 'io', NOW(), NOW()),
                  ('Icelandic', 'is', NOW(), NOW()),
                  ('Italian', 'it', NOW(), NOW()),
                  ('Inuktitut', 'iu', NOW(), NOW()),
                  ('Japanese', 'ja', NOW(), NOW()),
                  ('Javanese', 'jv', NOW(), NOW()),
                  ('Georgian', 'ka', NOW(), NOW()),
                  ('Kongo', 'kg', NOW(), NOW()),
                  ('Kikuyu', 'ki', NOW(), NOW()),
                  ('Kuanyama', 'kj', NOW(), NOW()),
                  ('Kazakh', 'kk', NOW(), NOW()),
                  ('Kalaallisut', 'kl', NOW(), NOW()),
                  ('Central Khmer', 'km', NOW(), NOW()),
                  ('Kannada', 'kn', NOW(), NOW()),
                  ('Korean', 'ko', NOW(), NOW()),
                  ('Kanuri', 'kr', NOW(), NOW()),
                  ('Kashmiri', 'ks', NOW(), NOW()),
                  ('Kurdish', 'ku', NOW(), NOW()),
                  ('Komi', 'kv', NOW(), NOW()),
                  ('Cornish', 'kw', NOW(), NOW()),
                  ('Kirghiz', 'ky', NOW(), NOW()),
                  ('Latin', 'la', NOW(), NOW()),
                  ('Luxembourgish', 'lb', NOW(), NOW()),
                  ('Ganda', 'lg', NOW(), NOW()),
                  ('Limburgish', 'li', NOW(), NOW()),
                  ('Lingala', 'ln', NOW(), NOW()),
                  ('Lao', 'lo', NOW(), NOW()),
                  ('Lithuanian', 'lt', NOW(), NOW()),
                  ('Luba-Katanga', 'lu', NOW(), NOW()),
                  ('Latvian', 'lv', NOW(), NOW()),
                  ('Malagasy', 'mg', NOW(), NOW()),
                  ('Marshallese', 'mh', NOW(), NOW()),
                  ('Maori', 'mi', NOW(), NOW()),
                  ('Macedonian', 'mk', NOW(), NOW()),
                  ('Malayalam', 'ml', NOW(), NOW()),
                  ('Mongolian', 'mn', NOW(), NOW()),
                  ('Marathi', 'mr', NOW(), NOW()),
                  ('Malay', 'ms', NOW(), NOW()),
                  ('Maltese', 'mt', NOW(), NOW()),
                  ('Burmese', 'my', NOW(), NOW()),
                  ('Nauru', 'na', NOW(), NOW()),
                  ('Norwegian Bokmål', 'nb', NOW(), NOW()),
                  ('North Ndebele', 'nd', NOW(), NOW()),
                  ('Nepali', 'ne', NOW(), NOW()),
                  ('Ndonga', 'ng', NOW(), NOW()),
                  ('Dutch', 'nl', NOW(), NOW()),
                  ('Norwegian Nynorsk', 'nn', NOW(), NOW()),
                  ('Norwegian', 'no', NOW(), NOW()),
                  ('South Ndebele', 'nr', NOW(), NOW()),
                  ('Navajo', 'nv', NOW(), NOW()),
                  ('Chichewa', 'ny', NOW(), NOW()),
                  ('Occitan', 'oc', NOW(), NOW()),
                  ('Ojibwe', 'oj', NOW(), NOW()),
                  ('Oromo', 'om', NOW(), NOW()),
                  ('Oriya', 'or', NOW(), NOW()),
                  ('Ossetian', 'os', NOW(), NOW()),
                  ('Punjabi', 'pa', NOW(), NOW()),
                  ('Pali', 'pi', NOW(), NOW()),
                  ('Polish', 'pl', NOW(), NOW()),
                  ('Pushto', 'ps', NOW(), NOW()),
                  ('Portuguese', 'pt', NOW(), NOW()),
                  ('Quechua', 'qu', NOW(), NOW()),
                  ('Romansh', 'rm', NOW(), NOW()),
                  ('Rundi', 'rn', NOW(), NOW()),
                  ('Romanian', 'ro', NOW(), NOW()),
                  ('Russian', 'ru', NOW(), NOW()),
                  ('Kinyarwanda', 'rw', NOW(), NOW()),
                  ('Sanskrit', 'sa', NOW(), NOW()),
                  ('Sardinian', 'sc', NOW(), NOW()),
                  ('Sindhi', 'sd', NOW(), NOW()),
                  ('Northern Sami', 'se', NOW(), NOW()),
                  ('Sango', 'sg', NOW(), NOW()),
                  ('Sinhalese', 'si', NOW(), NOW()),
                  ('Slovak', 'sk', NOW(), NOW()),
                  ('Slovenian', 'sl', NOW(), NOW()),
                  ('Samoan', 'sm', NOW(), NOW()),
                  ('Shona', 'sn', NOW(), NOW()),
                  ('Somali', 'so', NOW(), NOW()),
                  ('Albanian', 'sq', NOW(), NOW()),
                  ('Serbian', 'sr', NOW(), NOW()),
                  ('Swati', 'ss', NOW(), NOW()),
                  ('Southern Sotho', 'st', NOW(), NOW()),
                  ('Sundanese', 'su', NOW(), NOW()),
                  ('Swedish', 'sv', NOW(), NOW()),
                  ('Swahili', 'sw', NOW(), NOW()),
                  ('Tamil', 'ta', NOW(), NOW()),
                  ('Telugu', 'te', NOW(), NOW()),
                  ('Tajik', 'tg', NOW(), NOW()),
                  ('Thai', 'th', NOW(), NOW()),
                  ('Tigrinya', 'ti', NOW(), NOW()),
                  ('Turkmen', 'tk', NOW(), NOW()),
                  ('Tagalog', 'tl', NOW(), NOW()),
                  ('Tswana', 'tn', NOW(), NOW()),
                  ('Tonga', 'to', NOW(), NOW()),
                  ('Turkish', 'tr', NOW(), NOW()),
                  ('Tsonga', 'ts', NOW(), NOW()),
                  ('Tatar', 'tt', NOW(), NOW()),
                  ('Twi', 'tw', NOW(), NOW()),
                  ('Tahitian', 'ty', NOW(), NOW()),
                  ('Uighur', 'ug', NOW(), NOW()),
                  ('Ukrainian', 'uk', NOW(), NOW()),
                  ('Urdu', 'ur', NOW(), NOW()),
                  ('Uzbek', 'uz', NOW(), NOW()),
                  ('Venda', 've', NOW(), NOW()),
                  ('Vietnamese', 'vi', NOW(), NOW()),
                  ('Volapük', 'vo', NOW(), NOW()),
                  ('Walloon', 'wa', NOW(), NOW()),
                  ('Wolof', 'wo', NOW(), NOW()),
                  ('Xhosa', 'xh', NOW(), NOW()),
                  ('Yiddish', 'yi', NOW(), NOW()),
                  ('Yoruba', 'yo', NOW(), NOW()),
                  ('Zhuang', 'za', NOW(), NOW()),
                  ('Chinese', 'zh', NOW(), NOW()),
                  ('Zulu', 'zu', NOW(), NOW());
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DELETE FROM profile.language;
            ");
        }
    }
}
