const authorities = {
  CATALOG_MANAGE: 'CATALOG_MANAGE',
  ORDERS_MANAGE: 'ORDERS_MANAGE',
  REPORTING_MANAGE: 'REPORTING_MANAGE',
  SETTINGS_MANAGE: 'SETTINGS_MANAGE',
  USERS_MANAGE: 'USERS_MANAGE',
};

export default authorities;
